// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.cache.enabled", true);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.dom.quotaManager.backgroundTask.enabled", false);
user_pref("app.normandy.user_id", "a131acd4-9d82-4998-ba01-d070bde7076e");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1683214308);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1683214310);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1683436771);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{65e46e06-6356-44a5-a74e-ed9e018639ff}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1683214277);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{205d1898-3ec7-4bee-80ca-3b26422b7443}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1683214279);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1683436774055");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1683438593055");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1683436774595");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1683458374595");
user_pref("browser.search.region", "JP");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230424110519");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1683436771");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230424110519");
user_pref("browser.startup.homepage_override.mstone", "112.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1683436770);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"adblockultimate_adblockultimate_net-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"adblockultimate_adblockultimate_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"unified-extensions-area\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1683214279102");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "112.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "JP");
user_pref("dom.push.userAgentID", "4472ac5575ea489d919f815d4e9ec33d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1683436772);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230424110519");
user_pref("extensions.lastAppVersion", "112.0.2");
user_pref("extensions.lastPlatformVersion", "112.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.adblockultimate@adblockultimate.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"165aef5e-787d-41bf-a803-a10b9209c8ce\",\"pictureinpicture@mozilla.org\":\"02cdb9d4-a0e8-4cb7-a791-331680d3a4e3\",\"screenshots@mozilla.org\":\"337bbe9e-551a-4414-9548-7ae3f92d625b\",\"webcompat-reporter@mozilla.org\":\"c8be8474-655c-40ce-a573-1c91870b5d00\",\"webcompat@mozilla.org\":\"d1aa9327-6258-47f9-af43-ea287449ef73\",\"default-theme@mozilla.org\":\"3abdaddb-9a7a-480e-869f-0ab4862d3170\",\"addons-search-detection@mozilla.com\":\"3ba94d3c-a87a-4398-8635-278c35171afd\",\"google@search.mozilla.org\":\"ae6df8a4-a688-467e-84b8-230d20270e41\",\"wikipedia@search.mozilla.org\":\"a96c2337-302f-496c-890c-f3660029df0e\",\"yahoo-jp-auctions@search.mozilla.org\":\"a631994a-4c5f-4591-a062-9b5d6c30e4b2\",\"bing@search.mozilla.org\":\"8a168c23-cdae-4f82-b255-3640f1ab8158\",\"rakuten@search.mozilla.org\":\"b81a93f4-d8d1-4bf0-8766-424d406f566d\",\"yahoo-jp@search.mozilla.org\":\"d9a21741-594c-4969-be94-be257b1df3d9\",\"ddg@search.mozilla.org\":\"f94067e2-654f-4d31-aa5b-d7e9f986e68c\",\"amazon@search.mozilla.org\":\"a08b9705-98e4-4d8d-b6ef-c4fe4cd93925\",\"adblockultimate@adblockultimate.net\":\"54c78742-caf5-4eee-a863-29ca3a1357d8\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.accessibilityCache", "{\"slug\":\"next-generation-accessibility-engine-powering-screen-readers\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"accessibilityCache\"},\"features\":null},\"active\":true,\"enrollmentId\":\"fe225636-321d-4e51-9e36-456373366755\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Next generation accessibility engine powering screen readers\",\"userFacingDescription\":\"Evaluating a major re-architecture of Firefox's accessibility engine to improve performance of screen readers and other assistive technologies.\",\"lastSeen\":\"2023-05-04T15:31:49.179Z\",\"featureIds\":[\"accessibilityCache\"],\"prefs\":[{\"name\":\"accessibility.cache.enabled\",\"branch\":\"user\",\"featureId\":\"accessibilityCache\",\"variable\":\"enabled\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.accessibilityCache.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "d3bb1292-b5f6-48f5-8f69-9defcbbff3b1");
user_pref("toolkit.startup.last_success", 1683436768);
user_pref("toolkit.telemetry.cachedClientID", "3c4b1d90-8dd1-4ced-88e5-4732cffd6e54");
user_pref("toolkit.telemetry.previousBuildID", "20230424110519");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
