ARG BASE_TAG
FROM brownie_atelier_base:${BASE_TAG}

#LABELでメタ情報を入れることができる
LABEL maintainer="BrownieAtelierApp"

ARG CONTAINER_USER
ARG GIT_BRANCH

# リポジトリ一覧を更新、インストール済みのパッケージ更新
RUN echo ${CONTAINER_USER} | sudo -S apt-get update
RUN echo ${CONTAINER_USER} | sudo -S apt update
RUN echo ${CONTAINER_USER} | sudo -S apt -y upgrade

# アプリ用ディレクトリへ移動
WORKDIR /home/${CONTAINER_USER}/BrownieAtelier
# リモートリポジトリよりpullを実行し最新ソースを取得する。
RUN git pull origin ${GIT_BRANCH}
RUN git submodule update --recursive

# mongoDB初期化ツールを配置
RUN cp /home/${CONTAINER_USER}/BrownieAtelier/mongodb/init/create-user.js base_image_build.d
# シェルに実行権限を付与
WORKDIR /home/${CONTAINER_USER}/BrownieAtelier/sh
RUN chmod 755 ./*

# Pipfile.lockからインストール（更新があった場合）
WORKDIR /home/${CONTAINER_USER}/BrownieAtelier
RUN python3 -m pipenv sync
RUN .venv/bin/pip list

ENTRYPOINT []
CMD []
