services:
    brownie_atelier_news_crawler:
        build:
            context: .
            dockerfile: dockerfile_app
            args:
                ## dockerfile_appで参照するbase側のイメージタグ
                BASE_TAG: ${BASE_TAG}
                # コンテナ内の一般ユーザー、パスワード
                CONTAINER_USER: ${CONTAINER_USER}
                # ブラウニー工房のgitリモートリポジトリーのブランチ
                GIT_BRANCH: ${GIT_BRANCH}
        image: brownie_atelier_news_crawler:${APP_TAG}
