#FROM openjdk:11-stretch
FROM brownie_atelier_base:0.12

#LABELでメタ情報を入れることができる
#LABEL maintainer="Martijn Koster \"mak-docker@greenhills.co.uk\""
#LABEL repository="https://github.com/docker-solr/docker-solr"
LABEL maintainer="BrownieAtelier-app-test"

ARG NORMAL_USER
ARG GIT_REMOTE_REPOSITORY

# リポジトリ一覧を更新、インストール済みのパッケージ更新
RUN apt-get update
RUN apt update
RUN apt -y upgrade

# アプリ用ディレクトリへ移動
WORKDIR /home/${NORMAL_USER}/BrownieAtelier
# リモートリポジトリよりpullを実行し最新ソースを取得する。
# RUN git pull origin master
RUN git pull origin develop

# オーナー＆グループを一般ユーザーに変更 (上記はrootで実行されているため念の為)
WORKDIR /home/${NORMAL_USER}
RUN chown -R ${NORMAL_USER}:${NORMAL_USER} .

# コンテナ実行時のユーザーを一般ユーザーへ変更
USER ${NORMAL_USER}