services:
    brownie-atelier-news-crawler:
        build:
            context: .
            dockerfile: dockerfile
            args:
                ## dockerfileで参照するbase側のイメージタグ
                BASE_TAG: ${BASE_TAG}
                # ベースイメージ作成時と同じ一般ユーザー名（パスワードは不要）
                CONTAINER_USER: ${CONTAINER_USER}
                # ブラウニー工房のgitリモートリポジトリーのブランチ
                GIT_BRANCH: ${GIT_BRANCH}
        image: brownie-atelier-news-crawler:${NEWS_CRAWLER_TAG}
