ARG BASE_TAG
FROM brownie_atelier_news_crawler_base:${BASE_TAG}

#LABELでメタ情報を入れることができる
LABEL maintainer="BrownieAtelierNewsCrawler"

ARG CONTAINER_USER
ARG GIT_BRANCH

# リポジトリ一覧を更新、インストール済みのパッケージ更新
RUN echo ${CONTAINER_USER} | sudo -S apt-get update
RUN echo ${CONTAINER_USER} | sudo -S apt update
RUN echo ${CONTAINER_USER} | sudo -S apt -y upgrade

# アプリ用ディレクトリへ移動
WORKDIR /home/${CONTAINER_USER}/BrownieAtelierNewsCrawler

# リモートリポジトリよりpullを実行し最新ソースを取得する。
RUN git config pull.rebase false
RUN git pull origin "${GIT_BRANCH}"
RUN git submodule update --recursive

# シェルに実行権限を付与
WORKDIR /home/${CONTAINER_USER}/BrownieAtelierNewsCrawler/sh
RUN chmod 755 ./*
WORKDIR /home/${CONTAINER_USER}/BrownieAtelierNewsCrawler/data
RUN chmod 766 ./*
RUN ls -la

# Pipfile.lockからインストール（更新があった場合）
WORKDIR /home/${CONTAINER_USER}/BrownieAtelierNewsCrawler
RUN python3 -m pipenv sync
RUN ls -la
RUN .venv/bin/pip list

ENTRYPOINT []
CMD []
