name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    # 以下のブランチにプッシュされた際起動
    # push:
    #     branches: ["github-actions-test"]
    # Githubより手動で起動
    workflow_dispatch:

jobs:
  GitHub-Actions-Test:
    runs-on: ubuntu-22.04
    environment:
      name: TEST
    env:
        ## mongoDB用コンテナーで参照するイメージのタグ
        MONGO_TAG: 7.0.1-jammy
        ## dockerfile_baseで参照するubuntuイメージのタグ
        UBUNTU_TAG: 22.04
        ## # dockerfile_appで参照するbaseイメージのタグ
        BASE_TAG: test-0.15
        # docker-composeで参照するappイメージのタグ
        APP_TAG: test-0.15
        # コンテナー内rootユーザーパスワード
        CONTAINER_ROOT_USER: root_user
        CONTAINER_ROOT_PASS: password
        # コンテナ内の一般ユーザー、パスワード
        CONTAINER_USER: common_user
        CONTAINER_USER_PASS: password
        # ブラウニー工房のgitリモートリポジトリー
        GIT_REMOTE_REPOSITORY: https://github.com/pubranko/BrownieAtelierNewsCrawler.git
        # 上記リポジトリーのgitブランチ
        GIT_BRANCH: github-actions-test
        # Firefox の gecko driver
        GECKO_DRIVER: https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz

        # ホスト（ローカル）側のmongoDB接続用のcrtやpemファイルの保管ディレクトリ
        LOCAL_MONGO_KEY_DIR: /tmp

        # docker-compose command選択
        CONTAINER_START_COMMAND: /home/common_user/BrownieAtelierNewsCrawler/sh/github_actions_unit_test.sh

        # mongoDBコンテナー一般ユーザー情報、mongoDB接続情報
        BROWNIE_ATELIER_MONGO__MONGO_SERVER: mongo-server
        BROWNIE_ATELIER_MONGO__MONGO_PORT: 27017
        BROWNIE_ATELIER_MONGO__MONGO_USE_DB: test_crawler_db
        BROWNIE_ATELIER_MONGO__MONGO_USER: mongo_user
        BROWNIE_ATELIER_MONGO__MONGO_PASS: mongo_pass
        BROWNIE_ATELIER_MONGO__MONGO_TLS: false
        BROWNIE_ATELIER_MONGO__MONGO_TLS_CA_FILE:
        BROWNIE_ATELIER_MONGO__MONGO_TLS_CERTTIFICATE_KEY_FILE:
        # mongoDBコンテナーroot情報
        BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_USERNAME: root_user
        BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_PASSWORD: password
        # Email接続情報
        BROWNIE_ATELIER_NOTICE__SMTP_HOST: ${{ secrets.BROWNIE_ATELIER_NOTICE__SMTP_HOST }}
        BROWNIE_ATELIER_NOTICE__SMTP_PORT: ${{ secrets.BROWNIE_ATELIER_NOTICE__SMTP_PORT }}
        BROWNIE_ATELIER_NOTICE__FROM_EMAIL: ${{ secrets.BROWNIE_ATELIER_NOTICE__FROM_EMAIL }}
        BROWNIE_ATELIER_NOTICE__TO_EMAIL: ${{ secrets.BROWNIE_ATELIER_NOTICE__TO_EMAIL }}
        BROWNIE_ATELIER_NOTICE__PASSWORD: ${{ secrets.BROWNIE_ATELIER_NOTICE__PASSWORD }}

        # dummy
        HOST_OS_IP_ADDRESS: 192.0.0.1
        # dummy
        PREFECT_HOME: /home/root_user/BrownieAtelierNewsCrawler
        PREFECT_API_URL:
        PREFECT__API_KEY:
        PREFECT__WORK_SPACE:
        PREFECT__WORK_POOL:
        SCRAPY__LOG_LEVEL: INFO

        # Docker イメージの tar アーカイブ出力先のパス
        PATH_CACHE: /tmp/docker-img-arch
    steps:
      - run: echo "🎉 起動イベントの種類 (${{ github.event_name }})"
      - run: echo "🐧 github上のOSの種類 (${{ runner.os }})"
      - name: リポジトリ(${{ github.repository }})・ブランチ(${{ github.ref }})にチェックアウト
        # 上記のリポジトリ・ブランチにチェックアウト
        uses: actions/checkout@v4

      - name: ワークスペースチェック
        # テスト前チェックを確認
        # クローン後はここにソースが格納される /home/runner/work/BrownieAtelierNewsCrawler/BrownieAtelierNewsCrawler
        run: |
          ls -a ${{ github.workspace }}

      # インストールされているものの一覧を調べてみた。
      #- run: sudo apt list --installed
      #- run: sudo dpkg-query -l

      - name: dockerネットワークをテスト用に作成
        # dockerネットワークを作成
        run: docker network create brownie-atelier-net


      #################################################
      # mongoDBコンテナー
      #################################################
      - name: テスト用MongoDBコンテナーpull & 起動
        # mongoDBコンテナーの作成。
        #   rootユーザー、使用DB名を指定。
        #   一般ユーザーをcreate-user.jsで自動作成。
        run:  >
          docker run -d
          --name mongo-server
          -p 27017:27017
          --network brownie-atelier-net
          -v $PWD/mongodb/init/create-user.js:/docker-entrypoint-initdb.d/create-user.js
          -e MONGO_INITDB_ROOT_USERNAME=${BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_USERNAME}
          -e MONGO_INITDB_ROOT_PASSWORD=${BROWNIE_ATELIER_MONGO__MONGO_INITDB_ROOT_PASSWORD}
          -e BROWNIE_ATELIER_MONGO__MONGO_USE_DB=${BROWNIE_ATELIER_MONGO__MONGO_USE_DB}
          -e BROWNIE_ATELIER_MONGO__MONGO_USER=${BROWNIE_ATELIER_MONGO__MONGO_USER}
          -e BROWNIE_ATELIER_MONGO__MONGO_PASS=${BROWNIE_ATELIER_MONGO__MONGO_PASS}
          mongo:${MONGO_TAG}

      - run: |
          docker images
          docker ps -a

      #################################################
      # baseイメージコンテナー
      #################################################

      - name: baseイメージ用キャッシュの定義 & 復元
        # キャッシュID の定義
        id: base_image_cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PATH_CACHE }}
          key: ${{ runner.os }}-brownie_atelier_news_crawler_base-${{ env.BASE_TAG }}

      # キャッシュがある場合は tar をdockerにロードしてイメージに追加
      - name: base用キャッシュがある場合は tar をロードしてイメージ一覧に追加
        if: steps.base_image_cache.outputs.cache-hit == 'true'
        run: |
          ls -l ${{ env.PATH_CACHE }}
          docker load --input ${{ env.PATH_CACHE }}/${{ runner.os }}-brownie_atelier_news_crawler_base-${{ env.BASE_TAG }}.tar
          docker images

      - name: baseイメージがキャッシュにない場合にbuildとsave(キャッシュ)を実行
        if: steps.base_image_cache.outputs.cache-hit != 'true'
        run: |
          docker-compose -f docker-compose__base-image-build.yml build
          docker save brownie_atelier_news_crawler_base:$BASE_TAG -o ${{ env.PATH_CACHE }}/${{ runner.os }}-brownie_atelier_news_crawler_base-${{ env.BASE_TAG }}.tar
          ls -l ${{ env.PATH_CACHE }}
          docker images


      #################################################
      # appイメージコンテナー
      #################################################

      - name: appイメージbuild
        # appイメージ作成
        run: |
          docker-compose -f docker-compose__app-image-build.yml build
          docker images


      #################################################
      # appイメージコンテナーを起動して各種フロー実行
      #################################################

      - name: "<1>各ニュースサイト別スクレイピングの情報登録  <2>定期観測用のスパイダー登録  <3>初回定期観測"
        env:
          TZ: ${{ vars.TZ}}
        # 各種フローテスト
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_01.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<4>手動クローリング"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_02.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<5>定期観測のON/OFF  <6>定期観測"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_03.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<7>手動スクレイピング  <8>手動ニュースクリップマスター保存"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_04.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<9>Scrapy統計情報集計  <10>Scrapy統計情報レポート"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_05.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<11>スクレイピング使用パターンレポート  <12>同期チェック"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_06.py"
          docker-compose -f docker-compose__app-container.yml up

      - name: "<13>mongoDBエクスポート  <14>mongoDB削除  <15>mongoDBインポート"
        env:
          TZ: ${{ vars.TZ}}
        run: |
          export PREFECT_RUN_SCRIPT="prefect_lib/github_actions_unit_tests/github_actions_unit_test_07.py"
          docker-compose -f docker-compose__app-container.yml up

      # "🍏 This job's status is success."
      - run: echo "🍏 Job実行後のステータス： ${{ job.status }}."
